// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBG7WezXYWiQqeMpxBLt7rMoz6itOTyw',
    appId: '1:262904632156:web:b4a12a4ae43da5e42f2799',
    messagingSenderId: '262904632156',
    projectId: 'flutterfire-cli-test-f6f57',
    authDomain: 'flutterfire-cli-test-f6f57.firebaseapp.com',
    storageBucket: 'flutterfire-cli-test-f6f57.appspot.com',
    measurementId: 'G-NXRGDGCTBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjkbbyA7Z1jofEV0-eryJPWhhsASOkOaw',
    appId: '1:262904632156:android:eef79d5fec9aab142f2799',
    messagingSenderId: '262904632156',
    projectId: 'flutterfire-cli-test-f6f57',
    storageBucket: 'flutterfire-cli-test-f6f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKopB-r1-sAAc99XLfZ71dURkLHab1AJE',
    appId: '1:262904632156:ios:58c61e319713c6142f2799',
    messagingSenderId: '262904632156',
    projectId: 'flutterfire-cli-test-f6f57',
    storageBucket: 'flutterfire-cli-test-f6f57.appspot.com',
    iosClientId: '262904632156-v78rpqiosrn4i201sl1r75u8qt9egdl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKopB-r1-sAAc99XLfZ71dURkLHab1AJE',
    appId: '1:262904632156:ios:58c61e319713c6142f2799',
    messagingSenderId: '262904632156',
    projectId: 'flutterfire-cli-test-f6f57',
    storageBucket: 'flutterfire-cli-test-f6f57.appspot.com',
    iosClientId: '262904632156-v78rpqiosrn4i201sl1r75u8qt9egdl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestCli',
  );
}
