import 'dart:convert';
import 'dart:io';

import 'package:cli_util/cli_logging.dart';
import 'package:flutterfire_cli/src/firebase/firebase_options.dart';
import 'package:flutterfire_cli/src/firebase/firebase_web_writes.dart';
import 'package:flutterfire_cli/src/flutter_app.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

const _webOptions = FirebaseOptions(
  optionsSourceContent: '',
  optionsSourceFileName: 'firebase-options.json',
  apiKey: 'web-api-key',
  appId: '1:123:web:abc',
  messagingSenderId: '123',
  projectId: 'flutterfire-test',
  authDomain: 'flutterfire-test.firebaseapp.com',
  storageBucket: 'flutterfire-test.appspot.com',
  measurementId: 'G-ABC123',
);

Future<FlutterApp> _createFlutterApp(
  Directory directory, {
  required bool dependsOnMessaging,
}) async {
  await File(path.join(directory.path, 'pubspec.yaml')).writeAsString('''
name: test_app
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
${dependsOnMessaging ? '  firebase_messaging: ^15.0.0' : ''}
''');
  await Directory(path.join(directory.path, 'web')).create(recursive: true);

  return (await FlutterApp.load(directory))!;
}

void main() {
  group('webMessagingServiceWorkerContent()', () {
    test('loads the Firebase JS SDK version it is given', () {
      final content = webMessagingServiceWorkerContent(_webOptions, '12.19.0');

      expect(
        content,
        contains(
          "importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-app-compat.js');",
        ),
      );
      expect(
        content,
        contains(
          "importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-messaging-compat.js');",
        ),
      );
    });

    test('initializes Firebase with the web options', () {
      final content = webMessagingServiceWorkerContent(_webOptions, '12.19.0');

      final config = RegExp(
        r'firebase\.initializeApp\((\{[\s\S]*?\})\);',
      ).firstMatch(content);

      expect(config, isNotNull);
      expect(
        jsonDecode(config!.group(1)!),
        {
          'apiKey': 'web-api-key',
          'appId': '1:123:web:abc',
          'messagingSenderId': '123',
          'projectId': 'flutterfire-test',
          'authDomain': 'flutterfire-test.firebaseapp.com',
          'storageBucket': 'flutterfire-test.appspot.com',
          'measurementId': 'G-ABC123',
        },
      );
      expect(content, contains('firebase.messaging();'));
    });
  });

  group('writeWebMessagingServiceWorker()', () {
    late Directory appDirectory;

    setUp(() {
      appDirectory = Directory.systemTemp.createTempSync('flutterfire_cli_web');
    });

    tearDown(() {
      appDirectory.deleteSync(recursive: true);
    });

    test('writes the service worker into "web/"', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );

      final writtenPath = await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
      );

      expect(
        writtenPath,
        path.join(
          appDirectory.path,
          'web',
          webMessagingServiceWorkerFileName,
        ),
      );
      expect(
        File(writtenPath!).readAsStringSync(),
        startsWith('// File generated by FlutterFire CLI.'),
      );
    });

    test('refreshes a service worker it generated itself', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );
      final serviceWorker = File(
        path.join(
          appDirectory.path,
          'web',
          webMessagingServiceWorkerFileName,
        ),
      )..writeAsStringSync(
          webMessagingServiceWorkerContent(_webOptions, '1.0.0'),
        );

      final writtenPath = await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
      );

      expect(writtenPath, serviceWorker.path);
      expect(serviceWorker.readAsStringSync(), isNot(contains('1.0.0')));
    });

    test('keeps the code written below the marker', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );
      const handler = '''

messaging.onBackgroundMessage((message) => {
  console.log('Got a background message', message);
});
''';
      final serviceWorker = File(
        path.join(
          appDirectory.path,
          'web',
          webMessagingServiceWorkerFileName,
        ),
      )..writeAsStringSync(
          webMessagingServiceWorkerContent(
            _webOptions,
            '1.0.0',
            userSection: handler,
          ),
        );

      await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
      );

      final rewritten = serviceWorker.readAsStringSync();
      expect(rewritten, endsWith(handler));
      expect(rewritten, isNot(contains('1.0.0')));
    });

    test('leaves a generated file edited above the marker alone', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );
      final generated = webMessagingServiceWorkerContent(_webOptions, '1.0.0');
      // The user took the marker out and made the whole file theirs.
      final edited = generated.substring(0, generated.indexOf('// Your own'));
      final serviceWorker = File(
        path.join(
          appDirectory.path,
          'web',
          webMessagingServiceWorkerFileName,
        ),
      )..writeAsStringSync(edited);

      expect(
        await writeWebMessagingServiceWorker(
          flutterApp: flutterApp,
          webOptions: _webOptions,
          logger: Logger.standard(),
        ),
        isNull,
      );
      expect(serviceWorker.readAsStringSync(), edited);
    });

    test('leaves a hand written service worker alone', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );
      const handWritten = '// My own service worker\n';
      final serviceWorker = File(
        path.join(
          appDirectory.path,
          'web',
          webMessagingServiceWorkerFileName,
        ),
      )..writeAsStringSync(handWritten);

      final writtenPath = await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
      );

      expect(writtenPath, isNull);
      expect(serviceWorker.readAsStringSync(), handWritten);
    });

    test('does nothing when the app has no "web" directory', () async {
      final flutterApp = await _createFlutterApp(
        appDirectory,
        dependsOnMessaging: true,
      );
      Directory(path.join(appDirectory.path, 'web')).deleteSync();

      expect(
        await writeWebMessagingServiceWorker(
          flutterApp: flutterApp,
          webOptions: _webOptions,
          logger: Logger.standard(),
        ),
        isNull,
      );
    });
  });
}
