import 'dart:io';

import 'package:cli_util/cli_logging.dart';
import 'package:flutterfire_cli/src/commands/update.dart';
import 'package:flutterfire_cli/src/firebase/firebase_options.dart';
import 'package:flutterfire_cli/src/firebase/firebase_web_messaging_bundle.dart';
import 'package:flutterfire_cli/src/firebase/firebase_web_writes.dart';
import 'package:flutterfire_cli/src/flutter_app.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

const _webOptions = FirebaseOptions(
  optionsSourceContent: '',
  optionsSourceFileName: 'firebase-options.json',
  apiKey: 'web-api-key',
  appId: '1:123:web:abc',
  messagingSenderId: '123',
  projectId: 'flutterfire-test',
);

/// Stands in for npm and node: `npm install` creates `node_modules`, and
/// `node build.mjs` writes a fake bundle.
class _FakeNpm {
  _FakeNpm({this.npmAvailable = true});

  final bool npmAvailable;
  final calls = <String>[];

  Future<ProcessResult> call(
    String executable,
    List<String> arguments, {
    String? workingDirectory,
    bool runInShell = false,
  }) async {
    final command = '$executable ${arguments.join(' ')}';
    calls.add(command);

    if (executable == 'npm' && !npmAvailable) {
      throw ProcessException(executable, arguments);
    }
    if (command.startsWith('npm install')) {
      Directory(path.join(workingDirectory!, 'node_modules')).createSync();
    }
    if (command == 'node build.mjs') {
      File(path.join(workingDirectory!, 'out.js'))
          .writeAsStringSync('/* bundle */');
    }
    return ProcessResult(0, 0, '', '');
  }
}

Future<FlutterApp> _createFlutterApp(Directory directory) async {
  await File(path.join(directory.path, 'pubspec.yaml')).writeAsString('''
name: test_app
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.0.0
''');
  await Directory(path.join(directory.path, 'web')).create(recursive: true);

  return (await FlutterApp.load(directory))!;
}

void main() {
  late Directory appDirectory;
  late File serviceWorker;

  setUp(() {
    appDirectory = Directory.systemTemp.createTempSync('flutterfire_cli_sw');
    serviceWorker = File(
      path.join(appDirectory.path, 'web', 'firebase-messaging-sw.js'),
    );
  });

  tearDown(() {
    appDirectory.deleteSync(recursive: true);
  });

  group('WebMessagingServiceWorkerBundleInputs', () {
    test('round-trips through the header line', () {
      const inputs = WebMessagingServiceWorkerBundleInputs(
        firebaseConfig: {'apiKey': 'key', 'projectId': 'project'},
        firebaseJsSdkVersion: '12.19.0',
      );

      final parsed = WebMessagingServiceWorkerBundleInputs.parse(
        '// header\n${inputs.toHeaderLine()}\n\n/* bundle */',
      )!;

      expect(parsed.firebaseConfig, inputs.firebaseConfig);
      expect(parsed.firebaseJsSdkVersion, '12.19.0');
    });

    test('is null for a worker that was not bundled', () {
      expect(
        WebMessagingServiceWorkerBundleInputs.parse("importScripts('x');"),
        isNull,
      );
    });
  });

  test('the entry calls the default export of the user file', () {
    final entry = webMessagingServiceWorkerEntry(
      {'apiKey': 'key'},
      userFilePath: '/app/firebase-messaging-sw.user.js',
    );

    expect(
      entry,
      contains(
        'import * as userCode from "/app/firebase-messaging-sw.user.js";',
      ),
    );
    expect(entry, contains('userCode.default(messaging);'));
    expect(
      webMessagingServiceWorkerEntry({'apiKey': 'key'}),
      isNot(contains('userCode')),
    );
  });

  group('writeWebMessagingServiceWorker(bundle: true)', () {
    test('installs the SDK, bundles it and records the inputs', () async {
      final npm = _FakeNpm();

      final written = await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: npm.call,
      );

      expect(written, serviceWorker.path);
      expect(npm.calls, [
        'npm --version',
        'npm install --no-audit --no-fund --loglevel=error',
        'node build.mjs',
      ]);

      final content = serviceWorker.readAsStringSync();
      expect(content, startsWith('// File generated by FlutterFire CLI.'));
      expect(content, endsWith('/* bundle */'));
      expect(
        WebMessagingServiceWorkerBundleInputs.parse(content)!.firebaseConfig,
        containsPair('apiKey', 'web-api-key'),
      );
    });

    test('skips npm install when the SDK version is unchanged', () async {
      final flutterApp = await _createFlutterApp(appDirectory);
      final npm = _FakeNpm();

      for (var i = 0; i < 2; i++) {
        await writeWebMessagingServiceWorker(
          flutterApp: flutterApp,
          webOptions: _webOptions,
          logger: Logger.standard(),
          bundle: true,
          runProcess: npm.call,
        );
      }

      expect(npm.calls.where((c) => c.startsWith('npm install')), hasLength(1));
    });

    test('stays bundled when run again without the flag', () async {
      final flutterApp = await _createFlutterApp(appDirectory);
      final npm = _FakeNpm();

      await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: npm.call,
      );
      npm.calls.clear();

      await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
        runProcess: npm.call,
      );

      expect(npm.calls, contains('node build.mjs'));
      expect(
        serviceWorker.readAsStringSync(),
        isNot(contains('importScripts')),
      );
    });

    test('falls back to the compat worker without npm', () async {
      final written = await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: _FakeNpm(npmAvailable: false).call,
      );

      expect(written, serviceWorker.path);
      expect(serviceWorker.readAsStringSync(), contains('importScripts'));
    });

    test('leaves a bundled worker alone without npm', () async {
      final flutterApp = await _createFlutterApp(appDirectory);
      await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: _FakeNpm().call,
      );
      final bundled = serviceWorker.readAsStringSync();

      final written = await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
        runProcess: _FakeNpm(npmAvailable: false).call,
      );

      expect(written, isNull);
      expect(serviceWorker.readAsStringSync(), bundled);
    });

    test('does not drop code written below the compat marker', () async {
      final flutterApp = await _createFlutterApp(appDirectory);
      await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
      );
      serviceWorker.writeAsStringSync(
        '${serviceWorker.readAsStringSync()}messaging.onBackgroundMessage(f);\n',
      );
      final compat = serviceWorker.readAsStringSync();
      final npm = _FakeNpm();

      final written = await writeWebMessagingServiceWorker(
        flutterApp: flutterApp,
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: npm.call,
      );

      expect(written, isNull);
      expect(npm.calls, isEmpty);
      expect(serviceWorker.readAsStringSync(), compat);
    });
  });

  group('rebuildBundledWebMessagingServiceWorker()', () {
    test('rebuilds from the inputs recorded in the worker', () async {
      await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: _FakeNpm().call,
      );
      // What `flutter clean` does to the build directory.
      Directory(path.join(appDirectory.path, '.dart_tool'))
          .deleteSync(recursive: true);
      final npm = _FakeNpm();

      final written = await rebuildBundledWebMessagingServiceWorker(
        flutterAppPath: appDirectory.path,
        logger: Logger.standard(),
        runProcess: npm.call,
      );

      expect(written, serviceWorker.path);
      expect(npm.calls, contains('node build.mjs'));
      final entry = File(
        path.join(
          appDirectory.path,
          '.dart_tool',
          'flutterfire',
          'firebase-messaging-sw',
          'entry.js',
        ),
      ).readAsStringSync();
      expect(entry, contains('"apiKey": "web-api-key"'));
    });

    test('ignores a compat worker', () async {
      await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
      );
      final npm = _FakeNpm();

      expect(
        await rebuildBundledWebMessagingServiceWorker(
          flutterAppPath: appDirectory.path,
          logger: Logger.standard(),
          runProcess: npm.call,
        ),
        isNull,
      );
      expect(npm.calls, isEmpty);
    });

    test('runs as part of `flutterfire update`', () async {
      await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
        runProcess: _FakeNpm().call,
      );
      final npm = _FakeNpm();

      await updateFlutterFirePackages(
        flutterAppPath: appDirectory.path,
        logger: Logger.standard(),
        runProcess: (
          executable,
          arguments, {
          workingDirectory,
          runInShell = false,
        }) async =>
            ProcessResult(0, 0, '', ''),
        runNpm: npm.call,
      );

      expect(npm.calls, contains('node build.mjs'));
    });
  });

  test(
    'bundles a worker that runs the user code with real npm and esbuild',
    () async {
      File(path.join(appDirectory.path, 'firebase-messaging-sw.user.js'))
          .writeAsStringSync('''
import { onBackgroundMessage } from 'firebase/messaging/sw';

export default function (messaging) {
  onBackgroundMessage(messaging, (m) => console.log('USER_HANDLER', m));
}
''');

      final written = await writeWebMessagingServiceWorker(
        flutterApp: await _createFlutterApp(appDirectory),
        webOptions: _webOptions,
        logger: Logger.standard(),
        bundle: true,
      );

      expect(written, serviceWorker.path);
      final content = serviceWorker.readAsStringSync();
      expect(content, contains('USER_HANDLER'));
      expect(content, contains('web-api-key'));
      expect(content, isNot(contains('importScripts')));
      expect(content, isNot(contains('import ')));
    },
    skip: Process.runSync('npm', ['--version'], runInShell: true).exitCode != 0
        ? 'npm is not installed'
        : null,
    timeout: const Timeout(Duration(minutes: 3)),
  );
}
