import 'dart:io';

import 'package:flutterfire_cli/src/firebase/firebase_dart_configuration_write.dart';
import 'package:flutterfire_cli/src/firebase/firebase_options.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('FirebaseDartConfigurationWrite', () {
    void testWithWriter({
      required String testName,
      String? initialContent,
      FirebaseOptions? webOptions,
      FirebaseOptions? androidOptions,
      required void Function(String content) verify,
    }) {
      test(testName, () {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));

        final filePath = p.join(tempDir.path, 'lib', 'firebase_options.dart');
        final file = File(filePath)..createSync(recursive: true);
        if (initialContent != null) {
          file.writeAsStringSync(initialContent);
        }

        final writer = FirebaseDartConfigurationWrite(
          configurationFilePath: filePath,
          flutterAppPath: tempDir.path,
          firebaseProjectId: 'test-project-id',
          webOptions: webOptions,
          androidOptions: androidOptions,
        );

        writer.write();

        final updatedContent = file.readAsStringSync();
        verify(updatedContent);
      });
    }

    // Regression test for
    // https://github.com/invertase/flutterfire_cli/issues/422
    testWithWriter(
      testName:
          'replaces placeholder firebase_options.dart with generated output',
      initialContent: '''
// File normally generated by FlutterFire CLI. This is a stand-in.
// See README.md for details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // TODO: Remove this file and run `flutterfire config` for Firebase options
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'Generate this file by running `flutterfire configure`. '
      'See README.md for details.',
    );
  }
}
''',
      webOptions: const FirebaseOptions(
        optionsSourceContent: '{}',
        optionsSourceFileName: 'firebase-config.json',
        apiKey: 'api-key',
        appId: 'app-id',
        messagingSenderId: 'sender-id',
        projectId: 'test-project-id',
        measurementId: 'measurement-id',
        recaptchaSiteKey: 'recaptcha-site-key',
      ),
      verify: (updatedContent) {
        expect(updatedContent, contains('if (kIsWeb) {'));
        expect(updatedContent, contains('return web;'));
        expect(updatedContent, contains('static const FirebaseOptions web'));
        expect(updatedContent, isNot(contains('UnimplementedError')));
      },
    );

    testWithWriter(
      testName: 'generates correct output for JUST web (golden test)',
      webOptions: const FirebaseOptions(
        optionsSourceContent: '{}',
        optionsSourceFileName: 'firebase-config.json',
        apiKey: 'api-key',
        appId: 'app-id',
        messagingSenderId: 'sender-id',
        projectId: 'test-project-id',
        measurementId: 'measurement-id',
        recaptchaSiteKey: 'recaptcha-site-key',
      ),
      verify: (updatedContent) {
        final goldenFile = File('test/goldens/firebase_options_just_web.dart_');
        final expectedContent = goldenFile.readAsStringSync();
        expect(updatedContent, equals(expectedContent));
      },
    );

    testWithWriter(
      testName:
          'cleans up trailing empty lines when updating existing configuration',
      initialContent: '''
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'old-api-key',
  );

}
''',
      webOptions: const FirebaseOptions(
        optionsSourceContent: '{}',
        optionsSourceFileName: 'firebase-config.json',
        apiKey: 'new-api-key',
        appId: 'app-id',
        messagingSenderId: 'sender-id',
        projectId: 'test-project-id',
      ),
      verify: (updatedContent) {
        expect(updatedContent, contains(');\n}'));
        expect(updatedContent, isNot(contains(');\n\n}')));
        expect(updatedContent, isNot(contains('recaptchaSiteKey')));
      },
    );
  });
}
