import 'dart:io';

import 'package:flutterfire_cli/src/firebase/firebase_dart_configuration_write.dart';
import 'package:flutterfire_cli/src/firebase/firebase_options.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('FirebaseDartConfigurationWrite', () {
    // Regression test for
    // https://github.com/invertase/flutterfire_cli/issues/422
    test(
      'replaces placeholder firebase_options.dart with generated output',
      () {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));

        final filePath = p.join(tempDir.path, 'lib', 'firebase_options.dart');
        File(filePath)
          ..createSync(recursive: true)
          ..writeAsStringSync('''
// File normally generated by FlutterFire CLI. This is a stand-in.
// See README.md for details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // TODO: Remove this file and run `flutterfire config` for Firebase options
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'Generate this file by running `flutterfire configure`. '
      'See README.md for details.',
    );
  }
}
''');

        final writer = FirebaseDartConfigurationWrite(
          configurationFilePath: filePath,
          flutterAppPath: tempDir.path,
          firebaseProjectId: 'test-project-id',
          webOptions: const FirebaseOptions(
            optionsSourceContent: '{}',
            optionsSourceFileName: 'firebase-config.json',
            apiKey: 'api-key',
            appId: 'app-id',
            messagingSenderId: 'sender-id',
            projectId: 'test-project-id',
            measurementId: 'measurement-id',
          ),
        );

        writer.write();

        final updatedContent = File(filePath).readAsStringSync();
        expect(updatedContent, contains('if (kIsWeb) {'));
        expect(updatedContent, contains('return web;'));
        expect(updatedContent, contains('static const FirebaseOptions web'));
        expect(updatedContent, isNot(contains('UnimplementedError')));
      },
    );
  });
}
