/*
 * Copyright (c) 2016-present Invertase Limited & Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this library except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import 'dart:convert';
import 'dart:io';

import 'package:cli_util/cli_logging.dart';
import 'package:meta/meta.dart';
import 'package:path/path.dart' as path;

import '../common/strings.dart';
import '../flutter_app.dart';
import 'firebase_options.dart';

/// `firebase_messaging_web` registers this file, from the root of the built
/// web app, to receive messages while the app is in the background.
const webMessagingServiceWorkerFileName = 'firebase-messaging-sw.js';

/// Marks the file as generated. A `firebase-messaging-sw.js` without it is
/// treated as hand written and is never overwritten.
const _generatedFileHeader = '// File generated by FlutterFire CLI.';

/// Used when the Firebase JS SDK version cannot be read from the
/// `firebase_core_web` package the app resolves.
const _fallbackFirebaseJsSdkVersion = '12.19.0';

/// Writes the Firebase Cloud Messaging service worker to `web/`.
///
/// `firebase_messaging` on web cannot receive background messages without it,
/// and the Firebase configuration has to be duplicated into it because a
/// service worker cannot read `firebase_options.dart`.
///
/// Returns the path that was written, or `null` when nothing was written.
Future<String?> writeWebMessagingServiceWorker({
  required FlutterApp flutterApp,
  required FirebaseOptions webOptions,
  required Logger logger,
}) async {
  final webDirectory = flutterApp.webDirectory;
  if (!webDirectory.existsSync()) return null;

  final serviceWorkerFile = File(
    path.join(webDirectory.path, webMessagingServiceWorkerFileName),
  );

  if (serviceWorkerFile.existsSync()) {
    final existingContent = await serviceWorkerFile.readAsString();
    if (!existingContent.startsWith(_generatedFileHeader)) {
      logger.stdout(
        logSkippingExistingWebMessagingServiceWorker(serviceWorkerFile.path),
      );
      return null;
    }
  }

  final firebaseJsSdkVersion =
      await _firebaseJsSdkVersion(flutterApp.package.path);

  await serviceWorkerFile.writeAsString(
    webMessagingServiceWorkerContent(webOptions, firebaseJsSdkVersion),
  );

  return serviceWorkerFile.path;
}

@visibleForTesting
String webMessagingServiceWorkerContent(
  FirebaseOptions webOptions,
  String firebaseJsSdkVersion,
) {
  final firebaseConfig = <String, String>{
    'apiKey': webOptions.apiKey,
    'appId': webOptions.appId,
    'messagingSenderId': webOptions.messagingSenderId,
    'projectId': webOptions.projectId,
    if (webOptions.authDomain != null) 'authDomain': webOptions.authDomain!,
    if (webOptions.databaseURL != null) 'databaseURL': webOptions.databaseURL!,
    if (webOptions.storageBucket != null)
      'storageBucket': webOptions.storageBucket!,
    if (webOptions.measurementId != null)
      'measurementId': webOptions.measurementId!,
  };

  final cdn = 'https://www.gstatic.com/firebasejs/$firebaseJsSdkVersion';

  return '''
$_generatedFileHeader
//
// Service worker used by `firebase_messaging` to receive messages while your
// web app is in the background. A service worker cannot read
// `firebase_options.dart`, so the Firebase configuration is duplicated here.
//
// Running `flutterfire configure` again rewrites this file. Remove the header
// above to take ownership of it and the CLI will leave it alone.
//
// See https://firebase.google.com/docs/cloud-messaging/flutter/receive#web

importScripts('$cdn/firebase-app-compat.js');
importScripts('$cdn/firebase-messaging-compat.js');

firebase.initializeApp(${const JsonEncoder.withIndent('  ').convert(firebaseConfig)});

firebase.messaging();
''';
}

/// Reads the Firebase JS SDK version that `firebase_core_web` loads, so the
/// service worker runs the same SDK as the app itself.
Future<String> _firebaseJsSdkVersion(String flutterAppPath) async {
  try {
    final packageConfigFile = File(
      path.join(flutterAppPath, '.dart_tool', 'package_config.json'),
    );
    if (!packageConfigFile.existsSync()) return _fallbackFirebaseJsSdkVersion;

    final packageConfig =
        jsonDecode(await packageConfigFile.readAsString()) as Map;
    final packages = packageConfig['packages'] as List<dynamic>;

    final firebaseCoreWeb = packages.firstWhere(
      (dynamic package) =>
          package is Map && package['name'] == 'firebase_core_web',
      orElse: () => null,
    );
    if (firebaseCoreWeb == null) return _fallbackFirebaseJsSdkVersion;

    // "rootUri" is either absolute or relative to the ".dart_tool" directory.
    final rootUri = Uri.parse(
      (firebaseCoreWeb as Map)['rootUri'] as String,
    );
    final packageRoot = rootUri.isAbsolute
        ? rootUri.toFilePath()
        : path.normalize(
            path.join(
              path.dirname(packageConfigFile.path),
              rootUri.toFilePath(),
            ),
          );

    final sdkVersionFile = File(
      path.join(packageRoot, 'lib', 'src', 'firebase_sdk_version.dart'),
    );
    if (!sdkVersionFile.existsSync()) return _fallbackFirebaseJsSdkVersion;

    final match = RegExp(
      r'''supportedFirebaseJsSdkVersion\s*=\s*['"]([^'"]+)['"]''',
    ).firstMatch(await sdkVersionFile.readAsString());

    return match?.group(1) ?? _fallbackFirebaseJsSdkVersion;
  } catch (_) {
    return _fallbackFirebaseJsSdkVersion;
  }
}
