/*
 * Copyright (c) 2016-present Invertase Limited & Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this library except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import 'dart:convert';
import 'dart:io';

import 'package:cli_util/cli_logging.dart';
import 'package:meta/meta.dart';
import 'package:path/path.dart' as path;

import '../common/strings.dart';
import '../flutter_app.dart';
import 'firebase_options.dart';

/// `firebase_messaging_web` registers this file, from the root of the built
/// web app, to receive messages while the app is in the background.
const webMessagingServiceWorkerFileName = 'firebase-messaging-sw.js';

/// Marks the file as generated. A `firebase-messaging-sw.js` without it is
/// treated as hand written and is never overwritten.
const _generatedFileHeader = '// File generated by FlutterFire CLI.';

/// Everything below this line belongs to whoever edits the file, and is kept
/// as it is when the generated part above is refreshed.
///
/// Firebase's own documentation tells people to add their
/// `onBackgroundMessage` handler to this file, so rewriting it wholesale would
/// throw their code away.
const _userSectionMarker =
    '// Your own code goes below this line. FlutterFire CLI does not touch it.';

/// Used when the Firebase JS SDK version cannot be read from the
/// `firebase_core_web` package the app resolves.
const _fallbackFirebaseJsSdkVersion = '12.19.0';

/// Writes the Firebase Cloud Messaging service worker to `web/`.
///
/// `firebase_messaging` on web cannot receive background messages without it,
/// and the Firebase configuration has to be duplicated into it because a
/// service worker cannot read `firebase_options.dart`.
///
/// Returns the path that was written, or `null` when nothing was written.
Future<String?> writeWebMessagingServiceWorker({
  required FlutterApp flutterApp,
  required FirebaseOptions webOptions,
  required Logger logger,
}) async {
  final webDirectory = flutterApp.webDirectory;
  if (!webDirectory.existsSync()) return null;

  final serviceWorkerFile = File(
    path.join(webDirectory.path, webMessagingServiceWorkerFileName),
  );

  var userSection = '';

  if (serviceWorkerFile.existsSync()) {
    final existingContent = await serviceWorkerFile.readAsString();
    final markerIndex = existingContent.indexOf(_userSectionMarker);

    // Not ours, or ours but edited above the marker: either way the file is
    // the user's now.
    if (!existingContent.startsWith(_generatedFileHeader) || markerIndex < 0) {
      logger.stdout(
        logSkippingExistingWebMessagingServiceWorker(serviceWorkerFile.path),
      );
      return null;
    }

    userSection =
        existingContent.substring(markerIndex + _userSectionMarker.length);
  }

  final firebaseJsSdkVersion =
      await _firebaseJsSdkVersion(flutterApp.package.path);

  await serviceWorkerFile.writeAsString(
    webMessagingServiceWorkerContent(
      webOptions,
      firebaseJsSdkVersion,
      userSection: userSection,
    ),
  );

  return serviceWorkerFile.path;
}

@visibleForTesting
String webMessagingServiceWorkerContent(
  FirebaseOptions webOptions,
  String firebaseJsSdkVersion, {
  String userSection = '',
}) {
  final firebaseConfig = <String, String>{
    'apiKey': webOptions.apiKey,
    'appId': webOptions.appId,
    'messagingSenderId': webOptions.messagingSenderId,
    'projectId': webOptions.projectId,
    if (webOptions.authDomain != null) 'authDomain': webOptions.authDomain!,
    if (webOptions.databaseURL != null) 'databaseURL': webOptions.databaseURL!,
    if (webOptions.storageBucket != null)
      'storageBucket': webOptions.storageBucket!,
    if (webOptions.measurementId != null)
      'measurementId': webOptions.measurementId!,
  };

  final cdn = 'https://www.gstatic.com/firebasejs/$firebaseJsSdkVersion';

  return '''
$_generatedFileHeader
//
// Service worker used by `firebase_messaging` to receive messages while your
// web app is in the background. A service worker cannot read
// `firebase_options.dart`, so the Firebase configuration is duplicated here.
//
// Running `flutterfire configure` again refreshes everything above the marker
// at the bottom of this file, and keeps what is below it. Remove the header
// above to take ownership of the whole file and the CLI will leave it alone.
//
// See https://firebase.google.com/docs/cloud-messaging/flutter/receive#web

importScripts('$cdn/firebase-app-compat.js');
importScripts('$cdn/firebase-messaging-compat.js');

firebase.initializeApp(${const JsonEncoder.withIndent('  ').convert(firebaseConfig)});

const messaging = firebase.messaging();

$_userSectionMarker${userSection.isEmpty ? '\n' : userSection}''';
}

/// The `package_config.json` covering [flutterAppPath], or null if there is
/// none.
///
/// In a pub workspace the file lives at the workspace root rather than next to
/// the app's own `pubspec.yaml`, so parent directories are searched too.
File? _packageConfigFile(String flutterAppPath) {
  var directory = Directory(path.normalize(path.absolute(flutterAppPath)));

  while (true) {
    final packageConfigFile = File(
      path.join(directory.path, '.dart_tool', 'package_config.json'),
    );
    if (packageConfigFile.existsSync()) return packageConfigFile;

    final parent = directory.parent;
    if (parent.path == directory.path) return null;
    directory = parent;
  }
}

/// Reads the Firebase JS SDK version that `firebase_core_web` loads, so the
/// service worker runs the same SDK as the app itself.
Future<String> _firebaseJsSdkVersion(String flutterAppPath) async {
  try {
    final packageConfigFile = _packageConfigFile(flutterAppPath);
    if (packageConfigFile == null) return _fallbackFirebaseJsSdkVersion;

    final packageConfig =
        jsonDecode(await packageConfigFile.readAsString()) as Map;
    final packages = packageConfig['packages'] as List<dynamic>;

    final firebaseCoreWeb = packages.firstWhere(
      (dynamic package) =>
          package is Map && package['name'] == 'firebase_core_web',
      orElse: () => null,
    );
    if (firebaseCoreWeb == null) return _fallbackFirebaseJsSdkVersion;

    // "rootUri" is either absolute or relative to the ".dart_tool" directory.
    final rootUri = Uri.parse(
      (firebaseCoreWeb as Map)['rootUri'] as String,
    );
    final packageRoot = rootUri.isAbsolute
        ? rootUri.toFilePath()
        : path.normalize(
            path.join(
              path.dirname(packageConfigFile.path),
              rootUri.toFilePath(),
            ),
          );

    final sdkVersionFile = File(
      path.join(packageRoot, 'lib', 'src', 'firebase_sdk_version.dart'),
    );
    if (!sdkVersionFile.existsSync()) return _fallbackFirebaseJsSdkVersion;

    final match = RegExp(
      r'''supportedFirebaseJsSdkVersion\s*=\s*['"]([^'"]+)['"]''',
    ).firstMatch(await sdkVersionFile.readAsString());

    return match?.group(1) ?? _fallbackFirebaseJsSdkVersion;
  } catch (_) {
    return _fallbackFirebaseJsSdkVersion;
  }
}
